### PR TITLE
Switch to defaults for GHA maven verify

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slachiewicz** [comment]
I've been expecting to have here Java 21

**Comment by slawekjaranowski** [comment]
> I've been expecting to have here Java 21

I think we can try 21 in shared actions as default today

**Comment by khmarbaise** [comment]
Does Spotless  work with JDK 21 in the meantime?

**Review by khmarbaise — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
> Does Spotless work with JDK 21 in the meantime?
> 
> Yes rechecked it works with JDK 21 (2.40.0)...

Parent 4 has a workaround for Spotless and it is ready for JDK 21

**Pull request merged**
