### PR TITLE
[MINVOKER-296] Warn-log the case of incomplete name-description

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
It's seems I'm not following my own description/intention from the JIRA. Have to check it.

**Comment by pzygielo** [comment]
| invoker-report IT | has name | has description | warn for name | warn for description |
|---|---|---|---|---|
| failure-build | N | N | N | N |
| failure-post| N | Y | Y | N |
| failure-pre | Y | N | N | Y |
| skip-jre | N | Y | Y | N |
| skip-maven | N | Y | Y | N |
| skip-os | N | Y | Y | N |
| success | Y | Y | N | N |
| *expected warnings* | | | *4* | *1* |

**Comment by slawekjaranowski** [comment]
At the end please squash commits and add issue to commit subject

**Comment by pzygielo** [comment]
@slawekjaranowski - squashed.
Please review.

**Review by slawekjaranowski — APPROVED** [review]

**Comment by pzygielo** [comment]
Just out of curiosity of the failures on cloudbees - as I don't know where the jenkins pipeline source is stored and if it's publicly available at all. (If it is I'd be happy to learn its location.)

The master - green one:
```
$ curl --silent https://ci-maven.apache.org/blue/rest/organizations/jenkins/pipelines/Maven/pipelines/maven-github/pipelines/maven-invoker-plugin/branches/master/runs/1/log/?start=0 | grep -a "Fetching upstream"
Fetching upstream changes from https://gitbox.apache.org/repos/asf/maven-jenkins-env.git
Fetching upstream changes from https://gitbox.apache.org/repos/asf/maven-jenkins-lib.git
Fetching upstream changes from https://github.com/apache/maven-invoker-plugin.git
[...]
Fetching upstream changes from https://github.com/apache/maven-invoker-plugin.git
```
while the failing build for this PR:
```
$ curl --silent https://ci-maven.apache.org/blue/rest/organizations/jenkins/pipelines/Maven/pipelines/maven-github/pipelines/maven-invoker-plugin/branches/PR-97/runs/1/log/?start=0 | grep -a "Fetching upstream"
Fetching upstream changes from https://gitbox.apache.org/repos/asf/maven-jenkins-env.git
Fetching upstream changes from https://gitbox.apache.org/repos/asf/maven-jenkins-lib.git
```

So it seems that checkout of the project was not successful, however the build (next step I presume) was started regardless?

**Comment by slawekjaranowski** [comment]
Jenkins pipeline projects:
https://github.com/apache/maven-jenkins-lib
https://github.com/apache/maven-jenkins-env

**Comment by slawekjaranowski** [comment]
@olamy what happens here ... why some of check are green and some are red

**Comment by pzygielo** [comment]
> Jenkins pipeline projects: https://github.com/apache/maven-jenkins-lib https://github.com/apache/maven-jenkins-env

Oh I see, it's from here:
https://github.com/apache/maven-invoker-plugin/blob/0ab1c94bafc7a91722a0d22f49f75e6638fbbff6/Jenkinsfile#L20
\+ above. Thanks!

**Comment by jira-importer** [comment]
Resolve #543

**Pull request merged**
