### PR TITLE
[MINVOKER-274] use grooy-all pom but correctly

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by olamy** [comment]
@pzygielo

**Comment by pzygielo** [comment]
Not sure what is proposed here. Aren't the same commits merged already in #58?

**Comment by olamy** [comment]
@pzygielo  just get back to use groovy-all as before and as you tried with #59 but fixing the IT :)

**Comment by pzygielo** [comment]
Is there any commit waiting to be pushed?
I have only 212046e and ae1f114 listed.

**Comment by olamy** [comment]
doh not sure sure what happened with my git

**Comment by olamy** [comment]
@pzygielo  fix the mess with https://github.com/apache/maven-invoker-plugin/pull/62

**Comment by jira-importer** [comment]
Resolve #437

**Pull request closed without merging**
