### PR TITLE
[MINVOKER-364] Rename invoker.systemPropertiesFile to invoker.userPropertiesFile

### PR DESCRIPTION
**Pull request by slawekjaranowski**
https://issues.apache.org/jira/browse/MINVOKER-364

### CODE REVIEW

**Comment by olamy** [comment]
not sure I understand this naming change,
At the end of the day, those properties will be system properties used to fork the Maven invocation.
So they are the system properties of the Maven invocation you want to run.

**Comment by slawekjaranowski** [comment]
exactly it are a `user properties` passed by `-D` Maven argument
we have:

```
MAVEN_OPTS='-DsysProperty=xxx' mvn ... -DuserProperty=xxx
```

so `userProperty` it is a user property pass to Maven as cli argument

We cen set a system property by `MAVEN_OPTS` environment variable

**Comment by michael-o** [comment]
> not sure I understand this naming change, At the end of the day, those properties will be system properties used to fork the Maven invocation. So they are the system properties of the Maven invocation you want to run. you are confusing with Maven core naming but for an end user POV they are system properties. Those one you set using `-D...` when using the command line.

This has been a mess created long time ago. We need to clean up. Maven should use for itself user props only. If the JVM requires sys props they need to be set *before* Maven invocation. `System.setProperty()` cannot guarantee that the actual property is picked up by the receiver. Some read only at startup.

**Review by michael-o — APPROVED** [review]
Good -- needs another pair of eyes though.

**Review by olamy — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #592

**Pull request merged**
