### PR TITLE
[MINVOKER-257] Test code should meet checkstyle requirements

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by olamy** [comment]
@hboutemy @rfscholte maybe a rule for all of our code?? (checkstyle even for test).
honestly I'm really 0 with that... :) maybe even -1 :P

**Comment by slawekjaranowski** [comment]
I prepared this PR, because last time @Tibor17  ask about checkstyle in test code.
https://github.com/apache/maven-invoker-plugin/pull/7#issuecomment-549596895

**Comment by slachiewicz** [comment]
thx @slawekjaranowski for the patch!

**Comment by jira-importer** [comment]
Resolve #401

**Pull request closed without merging**
