### PR TITLE
[MINVOKER-255] support environmentVariable in invokerPropertiesFile

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by slachiewicz** [comment]
we have some merge conflicts and ITs build faild: https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-invoker-plugin/job/MINVOKER-255

could you check this?

**Comment by slawekjaranowski** [comment]
I've rebased code with current master and resolve merge conflicts.

As you see build on GA pass, please reset MINVOKER-255 to current code from my PR.
If problem will be still with build on jenkins I will see ...

**Comment by slawekjaranowski** [comment]
Can you show me errors from `...target/it/invocation-environmentvariable/build.log` from jenkins build 
or explain how can I see it. Reports "Maven Invoker Plugin Results" has invalid link

**Comment by slawekjaranowski** [comment]
I'v checked locally branch MINVOKER-255, with jdk7, 8, 13  - it is ok,
and on Github Action build also is ok.

Please simply rerun build on jenkis - sometime it can help

**Comment by slawekjaranowski** [comment]
Next rebase with master.

I added verify scripts which will shows build.log when some problem will occurs.

Please run this code on Jenkins, I will see what happen.

**Comment by slawekjaranowski** [comment]
hi, I rebase with current master and squash my commits to one.
Please update jenikns branch and run again.

**Pull request closed without merging**
