### PR TITLE
[MINVOKER-274] upgrade to groovy 3.0.8

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Comment by pzygielo** [comment]
Could `groovy-bom:pom` be imported and explicit version in all `groovy-*` dependencies skipped?

**Comment by olamy** [comment]
> Could `groovy-bom:pom` be imported and explicit version in all `groovy-*` dependencies skipped?

not sure how that helps here :)

**Comment by pzygielo** [comment]
IMO, it'd be more maven-way.

**Comment by olamy** [comment]
bom are useful for multi modules but no real value for a one module project.

**Comment by olamy** [comment]
I moved to use bom. frankly not really convince it's really useful in this case.... (compared to usage in parent poms)

**Pull request merged**
