### PR TITLE
[MINVOKER-271] fix detection of setup projects

### PR DESCRIPTION
**Pull request by slawekjaranowski**
fix implementation according to documentations on params:
 - invokerTest
 - pomExcludes
 - setupIncludes

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
kindly reminder about review

**Review by michael-o — COMMENTED** [review]
I have no idea how to properly review this. I need to pass here.

**Review by slawekjaranowski — COMMENTED** [review]
some comments why and what i changed - I hope it can help in review

**Comment by slawekjaranowski** [comment]
@slachiewicz , @cstamas ?

**Review by slachiewicz — APPROVED** [review]

**Review by cstamas — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
Thanks for approval.

@michael-o do you want to review also? ... or can be merged?

**Comment by slawekjaranowski** [comment]
@michael-o kindly reminder 😄

**Comment by michael-o** [comment]
> @michael-o kindly reminder 😄

TBH, no clue here. I have never worked on Invoker before. @cstamas If you are certain that the change is correct, please merge this month.

**Comment by slawekjaranowski** [comment]
@cstamas , @slachiewicz - so if no more remarks please merge.

**Pull request closed without merging**
