### PR TITLE
[MINVOKER-251] Allow options parallelThreads depends on available cores

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by Tibor17** [comment]
@slawekjaranowski Have you run the local build `mv verify -P run-its` before publishing the PR?

**Comment by slawekjaranowski** [comment]
yes, I have
```
[INFO] --- maven-invoker-plugin:3.2.0:verify (integration-test) @ maven-invoker-plugin ---
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 71, Failed: 0, Errors: 0, Skipped: 1
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:20 min

```

I see that you have enabled github action on your repository - maybe will be good add some action to run such job, or travis task.

If you want I can prepare some example for github action or for travis in another PR.

**Comment by Tibor17** [comment]
That's true and all 99 Maven projects need to have this!
Totally with you!
But I am afraid that GH Activities won't be propagated in your PR since it would happen after your commit. Not sure if the `$ git rebase` would trigger the build on existing old PR. We can try!

**Comment by Tibor17** [comment]
I was asking about the running the build because the `checkstyle` did not not break the build.
I don't know why. Maybe a profile has to be used for it but that should be always running. Why it is disabled?

**Comment by slawekjaranowski** [comment]
checkstyle didn't break build because property includeTestSourceDirectory for maven-checkstyle-plugin is by default set to false.

configuration for maven-checkstyle-plugin is in  artifact - maven-parent

**Comment by jira-importer** [comment]
Resolve #535

**Pull request merged**
